{% set version = "1.2.6.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-muhaz
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/muhaz_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/muhaz/muhaz_{{ version }}.tar.gz
  sha256: afa0102c13c108675c3f94a97bc17530bdf24fe3adef7623fbb06592bd42beb5

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-survival
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-survival

test:
  commands:
    - $R -e "library('muhaz')"           # [not win]
    - "\"%R%\" -e \"library('muhaz')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=muhaz
  license: GPL-2.0-or-later
  summary: Produces a smooth estimate of the hazard function for censored data.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: muhaz
# Description: Produces a smooth estimate of the hazard function for censored data.
# Version: 1.2.6.1
# Author: S original by Kenneth Hess, <khess@odin.mdacc.tmc.edu> R port by R. Gentleman
# Title: Hazard Function Estimation in Survival Analysis
# Depends: R(>= 2.3)
# Imports: survival
# License: GPL
# Maintainer: David Winsemius <dwinsemius@comcast.net>
# Packaged: 2019-01-26 16:15:38 UTC; hornik
# Repository: CRAN
# Date/Publication: 2019-01-26 16:43:07 UTC
# NeedsCompilation: yes
